package com.nbhysj.coupon.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nbhysj.coupon.model.response.SearchBean;
import com.nbhysj.coupon.model.response.CountryBean;

import com.nbhysj.coupon.greendao.SearchBeanDao;
import com.nbhysj.coupon.greendao.CountryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchBeanDaoConfig;
    private final DaoConfig countryBeanDaoConfig;

    private final SearchBeanDao searchBeanDao;
    private final CountryBeanDao countryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        countryBeanDaoConfig = daoConfigMap.get(CountryBeanDao.class).clone();
        countryBeanDaoConfig.initIdentityScope(type);

        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);
        countryBeanDao = new CountryBeanDao(countryBeanDaoConfig, this);

        registerDao(SearchBean.class, searchBeanDao);
        registerDao(CountryBean.class, countryBeanDao);
    }
    
    public void clear() {
        searchBeanDaoConfig.clearIdentityScope();
        countryBeanDaoConfig.clearIdentityScope();
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

    public CountryBeanDao getCountryBeanDao() {
        return countryBeanDao;
    }

}
