package com.nbhysj.coupon.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nbhysj.coupon.model.response.HomeSearchComprehensiveBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_SEARCH_COMPREHENSIVE_BEAN".
*/
public class HomeSearchComprehensiveBeanDao extends AbstractDao<HomeSearchComprehensiveBean, Long> {

    public static final String TABLENAME = "HOME_SEARCH_COMPREHENSIVE_BEAN";

    /**
     * Properties of entity HomeSearchComprehensiveBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Search = new Property(1, String.class, "search", false, "SEARCH");
    }


    public HomeSearchComprehensiveBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeSearchComprehensiveBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_SEARCH_COMPREHENSIVE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SEARCH\" TEXT);"); // 1: search
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_SEARCH_COMPREHENSIVE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeSearchComprehensiveBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String search = entity.getSearch();
        if (search != null) {
            stmt.bindString(2, search);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeSearchComprehensiveBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String search = entity.getSearch();
        if (search != null) {
            stmt.bindString(2, search);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeSearchComprehensiveBean readEntity(Cursor cursor, int offset) {
        HomeSearchComprehensiveBean entity = new HomeSearchComprehensiveBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // search
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeSearchComprehensiveBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSearch(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeSearchComprehensiveBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeSearchComprehensiveBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeSearchComprehensiveBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
